// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function s(prim) {
  return prim;
}

function ate(prim) {
  return prim;
}

var nope = null;

export {
  s ,
  ate ,
  nope ,
  
}
/* nope Not a pure module */
