// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var children = Props.children;
  return React.createElement("button", {
              className: "px-4 py-2 text-lg text-black border border-black cursor-pointer rounded-md"
            }, children);
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
