// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Card(Props) {
  var children = Props.children;
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var classes = className + "flex flex-col overflow-hidden bg-white rounded-lg\nshadow-lg";
  return React.createElement("div", {
              className: classes
            }, children);
}

var make = Card;

export {
  make ,
  
}
/* react Not a pure module */
