// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HeaderTsx from "./header.tsx";
import * as Footer$BlpBlog from "./footer.bs.js";

var make = HeaderTsx.default;

var Header = {
  make: make
};

function Layout(Props) {
  var children = Props.children;
  var className = Props.className;
  var mainClasses = "flex-1 w-full container p-4 mx-auto sm:p-8 " + className;
  return React.createElement("div", {
              className: "flex flex-col min-h-screen text-lg bg-gray-50"
            }, React.createElement(make, {}), React.createElement("main", {
                  className: mainClasses
                }, children), React.createElement(Footer$BlpBlog.make, {}));
}

var make$1 = Layout;

export {
  Header ,
  make$1 as make,
  
}
/* make Not a pure module */
