// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Re$BlpBlog from "../lib/Re.bs.js";
import * as Card$BlpBlog from "./Card.bs.js";

function MediaCard(Props) {
  var children = Props.children;
  var title = Props.title;
  return React.createElement(Card$BlpBlog.make, {
              children: React.createElement("div", {
                    className: "flex flex-col flex-1 p-6"
                  }, Re$BlpBlog.s(title), children),
              className: "relative w-full transition-all ease-in-out duration-200 group transform hover:translate-y-px hover:shadow-md"
            });
}

var make = MediaCard;

export {
  make ,
  
}
/* react Not a pure module */
