// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Lodash from "lodash";
import * as Link from "next/link";
import * as Re$BlpBlog from "../lib/Re.bs.js";
import * as TagJsx from "../images/heroicons/solid/Tag.jsx";

var tagComponent = TagJsx.default;

function make(tag) {
  return React.createElement("li", {
              className: "relative z-10 inline-block p-2 mb-2 mr-2 text-xs text-blue-700 rounded bg-blue-50"
            }, React.createElement(Link.default, {
                  href: "/tags/[slug]",
                  as: "/tags/" + Lodash.kebabCase(tag),
                  children: React.createElement("a", {
                        className: "flex items-end text-blue-700 hover:opacity-75"
                      }, React.createElement("tagComponent", {
                            className: "block w-4 h-4 mr-1 text-key"
                          }), Re$BlpBlog.s(tag))
                }));
}

export {
  tagComponent ,
  make ,
  
}
/* tagComponent Not a pure module */
