// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DateFns from "date-fns";
import * as Re$BlpBlog from "../lib/Re.bs.js";

function make(post) {
  var parsedDate = new Date(post.data.date);
  var published = DateFns.formatDistanceToNow(parsedDate);
  return React.createElement("div", {
              className: "flex items-center"
            }, React.createElement("p", {
                  className: "text-sm text-gray-700"
                }, React.createElement("span", undefined, Re$BlpBlog.s("Published " + (published + " ago."))), React.createElement("span", undefined, Re$BlpBlog.s(" \xe2\x80\xa2 ")), React.createElement("span", undefined, Re$BlpBlog.s(post.data.timeToRead))));
}

export {
  make ,
  
}
/* react Not a pure module */
