// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DotsHorizontalJsx from "../images/heroicons/solid/DotsHorizontal.jsx";

var dots = DotsHorizontalJsx.default;

function make(param) {
  React.useState(function () {
        return false;
      });
  
}

export {
  dots ,
  make ,
  
}
/* dots Not a pure module */
