// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Head from "next/head";
import * as Re$BlpBlog from "../lib/Re.bs.js";

function SEO(Props) {
  var title = Props.title;
  var description = Props.description;
  var imageOpt = Props.image;
  var image = imageOpt !== undefined ? imageOpt : "";
  return React.createElement(Head.default, {
              children: null
            }, React.createElement("title", undefined, Re$BlpBlog.s(title + " | Brandon Pittman")), React.createElement("meta", {
                  content: description,
                  name: "description"
                }), React.createElement("meta", {
                  content: "summary",
                  name: "twitter:card"
                }), React.createElement("meta", {
                  content: "@brandonpittman",
                  name: "twitter:creator"
                }), React.createElement("meta", {
                  content: title,
                  name: "twitter:title"
                }), React.createElement("meta", {
                  content: image,
                  name: "twitter:image"
                }), React.createElement("meta", {
                  content: description,
                  name: "twitter:description"
                }), React.createElement("meta", {
                  content: title,
                  property: "og:title"
                }), React.createElement("meta", {
                  content: description,
                  property: "og:description"
                }), React.createElement("meta", {
                  content: "website",
                  property: "og:type"
                }), React.createElement("meta", {
                  content: image,
                  property: "og:image"
                }));
}

var make = SEO;

export {
  make ,
  
}
/* react Not a pure module */
